{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "switchboard.fullname" . }}
  labels:
    {{- include "switchboard.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "switchboard.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8081
        - protocol: TCP
          port: 9090
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        {{- toYaml .Values.networkPolicy.dependencyPorts | nindent 8 }}
{{- end }}

