{{- range $component := list "control-plane" "distribution" }}
{{- $context := dict "root" $ "component" $component }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "switchboard.componentName" $context }}
  labels:
    {{- include "switchboard.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
automountServiceAccountToken: false
{{- end }}

